/**
 * ZAI UI Kit Catalog — shadcn-compatible Registry Route
 * GET /r/[name] → returns shadcn registry-item JSON for any pattern
 *
 * Example: /r/split-screen → JSON with component code, CSS vars, metadata
 */

import { NextRequest, NextResponse } from 'next/server'
import { PATTERNS, TOKENS } from '../../../data/layout-data'

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ name: string }> }
) {
  const { name } = await params
  const pattern = PATTERNS.find(p => p.id === name)

  if (!pattern) {
    return NextResponse.json(
      { error: 'Pattern not found', name },
      { status: 404 }
    )
  }

  // Resolve tokens referenced by this pattern
  const referencedTokens = pattern.tokenRefs
    .map(ref => TOKENS.find(t => t.id === ref))
    .filter(Boolean)

  // Build cssVars object — each token becomes a light + dark entry
  const cssVarsLight: Record<string, string> = {}
  const cssVarsDark: Record<string, string> = {}

  for (const token of referencedTokens) {
    if (!token) continue
    // For now, both light and dark use the same token value
    // (skins override these at :root level)
    cssVarsLight[token.cssVar] = token.cssValue
    cssVarsDark[token.cssVar] = token.cssValue
  }

  // Generate React component code
  const componentCode = generateComponentCode(pattern, referencedTokens)

  // Generate CSS file content
  const cssCode = generateCssFile(pattern, referencedTokens)

  const registryItem = {
    $schema: 'https://ui.shadcn.com/schema/registry-item.json',
    name: pattern.id,
    type: 'registry:block',
    title: pattern.name,
    description: `${pattern.name} layout pattern — ${pattern.type} based, category: ${pattern.category}`,
    author: 'zai-ui-kit',
    cssVars: {
      light: cssVarsLight,
      dark: cssVarsDark,
    },
    files: [
      {
        name: `${pattern.id}.tsx`,
        content: componentCode,
      },
      {
        name: `${pattern.id}.css`,
        content: cssCode,
      },
    ],
    categories: [pattern.category],
  }

  return NextResponse.json(registryItem, {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
      'Cache-Control': 'public, max-age=3600',
    },
  })
}

// ── Code generators ──────────────────────────────────────────────

function generateComponentCode(
  pattern: typeof PATTERNS[number],
  tokens: (typeof TOKENS[number] | undefined)[]
): string {
  const colToken = tokens.find(t => t?.group === 'COL')
  const rowToken = tokens.find(t => t?.group === 'ROW')
  const gapToken = tokens.find(t => t?.group === 'GAP')

  const lines: string[] = []
  lines.push(`/**`)
  lines.push(` * ${pattern.name} — Layout Pattern`)
  lines.push(` * Generated by @zai/ui-kit catalog`)
  lines.push(` */`)
  lines.push(``)
  lines.push(`import React from 'react'`)
  lines.push(``)
  lines.push(`interface ${pascalCase(pattern.id)}Props {`)
  lines.push(`  children?: React.ReactNode`)
  lines.push(`  className?: string`)
  lines.push(`}`)
  lines.push(``)
  lines.push(`export function ${pascalCase(pattern.id)}({ children, className }: ${pascalCase(pattern.id)}Props) {`)
  lines.push(`  return (`)
  lines.push(`    <div`)
  lines.push(`      className={className}`)
  lines.push(`      style={{`)
  lines.push(`        display: 'grid',`)

  if (pattern.cols) {
    lines.push(`        gridTemplateColumns: 'var(${colToken?.cssVar ?? '--zai-cols-equal-2'})',`)
  }
  if (pattern.rows) {
    lines.push(`        gridTemplateRows: 'var(${rowToken?.cssVar ?? '--zai-rows-auto'})',`)
  }
  if (pattern.gap) {
    lines.push(`        gap: 'var(${gapToken?.cssVar ?? '--zai-gap-xs'})',`)
  }
  if (pattern.areas) {
    lines.push(`        gridTemplateAreas: '${pattern.areas}',`)
  }
  if (pattern.autoRows) {
    lines.push(`        gridAutoRows: '1fr',`)
  }
  if (pattern.autoFlow) {
    lines.push(`        gridAutoFlow: '${pattern.autoFlow}',`)
  }
  lines.push(`        minHeight: '100%',`)
  lines.push(`      }}`)
  lines.push(`    >`)
  lines.push(`      {children}`)
  lines.push(`    </div>`)
  lines.push(`  )`)
  lines.push(`}`)
  lines.push(``)
  lines.push(`export default ${pascalCase(pattern.id)}`)

  return lines.join('\n')
}

function generateCssFile(
  pattern: typeof PATTERNS[number],
  tokens: (typeof TOKENS[number] | undefined)[]
): string {
  const lines: string[] = []
  lines.push(`/* ${pattern.name} — Layout Token References */`)
  lines.push(`/* Generated by @zai/ui-kit catalog */`)
  lines.push(``)

  for (const token of tokens) {
    if (!token) continue
    lines.push(`/* ${token.label}: ${token.cssValue} */`)
    lines.push(`/* var(${token.cssVar}) */`)
    lines.push(``)
  }

  lines.push(`.${pattern.id}-layout {`)
  if (pattern.cols) {
    const colToken = tokens.find(t => t?.group === 'COL')
    lines.push(`  grid-template-columns: var(${colToken?.cssVar ?? '--zai-cols-equal-2'});`)
  }
  if (pattern.rows) {
    const rowToken = tokens.find(t => t?.group === 'ROW')
    lines.push(`  grid-template-rows: var(${rowToken?.cssVar ?? '--zai-rows-auto'});`)
  }
  if (pattern.gap) {
    const gapToken = tokens.find(t => t?.group === 'GAP')
    lines.push(`  gap: var(${gapToken?.cssVar ?? '--zai-gap-xs'});`)
  }
  if (pattern.areas) {
    lines.push(`  grid-template-areas: ${pattern.areas};`)
  }
  if (pattern.autoRows) {
    lines.push(`  grid-auto-rows: 1fr;`)
  }
  if (pattern.autoFlow) {
    lines.push(`  grid-auto-flow: ${pattern.autoFlow};`)
  }
  lines.push(`}`)

  return lines.join('\n')
}

function pascalCase(kebab: string): string {
  return kebab
    .split('-')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}
